# https://rust-lang.github.io/rustfmt

edition = "2024"

binop_separator = "Back"
combine_control_expr = false
condense_wildcard_suffixes = true
error_on_line_overflow = true
error_on_unformatted = true
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Crate"
match_arm_blocks = false
match_block_trailing_comma = true
newline_style = "Auto"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
required_version = "1.8.0"
single_line_if_else_max_width = 0
use_field_init_shorthand = true
unstable_features = true
use_try_shorthand = true
wrap_comments = true
